### ISSUE TITLE
Is It works for Wordpress Login?

### ISSUE THREAD

**Issue by AndrexOfficial** [stevederico/SDLoginKit#5]
Hi, I'm wondering If it works for a Wordpress site, If yes how can I implement a wordpress login system?
Thanks

**Comment by stevederico** [comment]
This is a generic logic system, you can use it to work with whatever backend you have.   

I can't tell you how to implement it with wordpress, but it will work.  

Thanks,
Steve Derico
(415) 997-9706
http://bixbyapps.com
